import express from "express";
import parseText from "../controllers/resume/parsetext.js";
import parseJson from "../controllers/resume/parsejson.js";
import jsonToPdf from "../controllers/resume/jsontopdf.js";
import protectUser from "../middleware/protectuser.js";
import addResume from "../controllers/resume/addresume.js";
import customizeResume from "../controllers/resume/customizeresume.js";
import saveResume from "../controllers/resume/saveresume.js";
import updateDefaultResume from "../controllers/resume/updatedefaultresume.js";
import getAllResumes from "../controllers/resume/getallresumes.js";
import makeprimary from "../controllers/resume/makeprimary.js";
import deleteReusume from "../controllers/resume/deleteresume.js";
import resumeFromScratch from "../controllers/resume/resumefromscratch.js";
import getResumeById from "../controllers/resume/getresumebyid.js";
import updateResume from "../controllers/resume/updateresume.js";
import rewriteSummary from "../controllers/resume/rewritesummary.js";
const router = express.Router();

router.route("/parse-text").post(parseText);
router.route("/parse-json").post(parseJson);
router.route("/json-to-pdf").post(jsonToPdf);
router.route("/addresume").post(protectUser, addResume);
router.route("/customize-resume").post(protectUser, customizeResume);
router.route("/saveresume").post(protectUser, saveResume);
router.route("/update-defaultresume").post(protectUser, updateDefaultResume);
router.route("/getallresume", protectUser).get(protectUser, getAllResumes);
router.route("/make-primary").post(protectUser, makeprimary);
router.route("/delete-resume/:id").delete(protectUser, deleteReusume);
router.route("/resume-scratch").get(protectUser, resumeFromScratch);
router.route("/update-resume").post(protectUser, updateResume);
router.route("/getresume").post(protectUser, getResumeById);

router.route("/rewrite-summary").post(protectUser, rewriteSummary);
export default router;
